name: Build Extension Zip

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - cursor/fix-edge-insert-bug-and-update-readme-7f1c

permissions:
  contents: write

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: ver
        run: |
          echo "version=$(node -p "require('./edge-prompt-templates/manifest.json').version")" >> $GITHUB_OUTPUT

      - name: Verify manifest exists
        run: |
          test -f edge-prompt-templates/manifest.json

      - name: Create single-layer zip (first layer is folder)
        run: |
          zip -r edge-prompt-templates-v${{ steps.ver.outputs.version }}.zip edge-prompt-templates

      - name: Upload artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: edge-prompt-templates-v${{ steps.ver.outputs.version }}
          path: edge-prompt-templates-v${{ steps.ver.outputs.version }}.zip
          if-no-files-found: error

      - name: Publish GitHub Release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.ver.outputs.version }}
          name: edge-prompt-templates v${{ steps.ver.outputs.version }}
          draft: false
          prerelease: false
          files: edge-prompt-templates-v${{ steps.ver.outputs.version }}.zip